/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.AlunosBean;
import control.AlunosControl;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Deivid Facio
 */
public class Alunos extends javax.swing.JFrame {

    List<AlunosBean> listaAlunos;
    String tipoCadastro = "null";

    /**
     * Creates new form Alunos
     */
    public Alunos() {
        initComponents();
        listarAlunos();
        btSalvar.setEnabled(false);
        btCancelar.setEnabled(false);

    }

    private void cadastrarAluno() throws SQLException {
        AlunosBean aln = new AlunosBean();
        aln.setNomeAluno(jtfNome.getText().trim());
        aln.setCpfAluno(jtfCPF.getText().trim());
        aln.setEmailAluno(jtfEmail.getText().trim());
        aln.setCelAluno(jtfCelular.getText().trim());
        aln.setEndAluno(jtfEndereco.getText().trim());

        if (aln.getNomeAluno().isEmpty() || aln.getCpfAluno().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome e CPF são campos obrigatórios.");
            return;
        }

        AlunosControl a = new AlunosControl();
        a.cadastrarAluno(aln);
        JOptionPane.showMessageDialog(this, "Aluno cadastrado com sucesso!");
    }

    private void alterarAluno() throws SQLException {
        AlunosBean aln = new AlunosBean();
        aln.setIdAluno(Integer.parseInt(jtfID.getText()));
        aln.setNomeAluno(jtfNome.getText().trim());
        aln.setCpfAluno(jtfCPF.getText().trim());
        aln.setEmailAluno(jtfEmail.getText().trim());
        aln.setCelAluno(jtfCelular.getText().trim());
        aln.setEndAluno(jtfEndereco.getText().trim());

        if (aln.getNomeAluno().isEmpty() || aln.getCpfAluno().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome e CPF são campos obrigatórios.");
            return;
        }

        AlunosControl a = new AlunosControl();
        a.alterarAluno(aln);
        JOptionPane.showMessageDialog(this, "Aluno Alterado com Sucesso!");
    }

    protected void alunoSelecionado(JComboBox cbt) {
        if (jcbAlunos.getSelectedIndex() != -1) {
            jtfID.setText(String.valueOf(listaAlunos.get(cbt.getSelectedIndex()).getIdAluno()));
            jtfNome.setText(String.valueOf(listaAlunos.get(cbt.getSelectedIndex()).getNomeAluno()));
            jtfCPF.setText(String.valueOf(listaAlunos.get(cbt.getSelectedIndex()).getCpfAluno()));
            jtfEmail.setText(String.valueOf(listaAlunos.get(cbt.getSelectedIndex()).getEmailAluno()));
            jtfCelular.setText(String.valueOf(listaAlunos.get(cbt.getSelectedIndex()).getCelAluno()));
            jtfEndereco.setText(String.valueOf(listaAlunos.get(cbt.getSelectedIndex()).getEndAluno()));
        } else {

            jtfID.setText("");
            jtfNome.setText("");
            jtfCPF.setText("");
            jtfEmail.setText("");
            jtfCelular.setText("");
            jtfEndereco.setText("");
        }
    }

    private void listarAlunos() {
        AlunosControl aln = new AlunosControl();
        listaAlunos = aln.listarAlunos();
        jcbAlunos.removeAllItems();
        for (int i = 0; i < listaAlunos.size(); i++) {
            jcbAlunos.addItem(listaAlunos.get(i).getNomeAluno());
        }
    }

    private void limparCampos() {
        jtfID.setText("");
        jtfNome.setText("");
        jtfCPF.setText("");
        jtfEmail.setText("");
        jtfCelular.setText("");
        jtfEndereco.setText("");

    }

    private void desabilitarCampos() {

        jtfID.setEnabled(false);
        jtfNome.setEnabled(false);
        jtfCPF.setEnabled(false);
        jtfEmail.setEnabled(false);
        jtfCelular.setEnabled(false);
        jtfEndereco.setEnabled(false);
    }

    private void habilitarCampos() {

        jtfID.setEnabled(false);
        jtfNome.setEnabled(true);
        jtfCPF.setEnabled(true);
        jtfEmail.setEnabled(true);
        jtfCelular.setEnabled(true);
        jtfEndereco.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbID = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbCPF = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbCelular = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        btNovo = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jtfID = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfCPF = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jtfCelular = new javax.swing.JTextField();
        jtfEndereco = new javax.swing.JTextField();
        jcbAlunos = new javax.swing.JComboBox();
        btExcluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbID.setText("ID:");

        lbNome.setText("Nome:");

        lbCPF.setText("CPF:");

        lbEmail.setText("E-mail:");

        lbCelular.setText("Celular:");

        lbEndereco.setText("Endereço: ");

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jtfID.setEnabled(false);

        jtfNome.setEnabled(false);

        jtfCPF.setEnabled(false);

        jtfEmail.setEnabled(false);

        jtfCelular.setEnabled(false);
        jtfCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCelularActionPerformed(evt);
            }
        });

        jtfEndereco.setEnabled(false);

        jcbAlunos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbAlunosItemStateChanged(evt);
            }
        });
        jcbAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlunosActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("CADASTRO ALUNOS ETEC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEndereco)
                            .addComponent(lbCelular)
                            .addComponent(lbEmail)
                            .addComponent(lbCPF)
                            .addComponent(lbNome)
                            .addComponent(lbID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfID)
                            .addComponent(jtfNome)
                            .addComponent(jtfCPF)
                            .addComponent(jtfEmail)
                            .addComponent(jtfCelular)
                            .addComponent(jtfEndereco)
                            .addComponent(jcbAlunos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAlterar, btCancelar, btNovo, btSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jcbAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID)
                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCPF)
                    .addComponent(jtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCelular)
                    .addComponent(jtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo)
                    .addComponent(btAlterar)
                    .addComponent(btSalvar)
                    .addComponent(btCancelar)
                    .addComponent(btExcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        tipoCadastro = "novo";
        jtfNome.setEnabled(true);
        jtfCPF.setEnabled(true);
        jtfEmail.setEnabled(true);
        jtfCelular.setEnabled(true);
        jtfEndereco.setEnabled(true);
        jtfID.setEnabled(false);
        btCancelar.setEnabled(true);
        btSalvar.setEnabled(true);
        btAlterar.setEnabled(false);
        btNovo.setEnabled(false);
        btExcluir.setEnabled(false);
        limparCampos();
        habilitarCampos();

    }//GEN-LAST:event_btNovoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed

        if ("alterar".equals(tipoCadastro)) {
            alunoSelecionado(jcbAlunos);
        }

        desabilitarCampos();
        btSalvar.setEnabled(false);
        btCancelar.setEnabled(false);
        btNovo.setEnabled(true);
        btAlterar.setEnabled(true);
        btExcluir.setEnabled(true);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void jtfCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCelularActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        switch (tipoCadastro) {

            case "novo": {
                try {
                    cadastrarAluno();
                } catch (SQLException ex) {
                    Logger.getLogger(Alunos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            break;

            case "alterar": {
                try {
                    alterarAluno();
                } catch (SQLException ex) {
                    Logger.getLogger(Alunos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            break;
        }

        listarAlunos();
        desabilitarCampos();
        btSalvar.setEnabled(false);
        btCancelar.setEnabled(false);
        btNovo.setEnabled(true);
        btAlterar.setEnabled(true);
        btExcluir.setEnabled(true);


    }//GEN-LAST:event_btSalvarActionPerformed

    private void jcbAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAlunosActionPerformed

    private void jcbAlunosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbAlunosItemStateChanged
        alunoSelecionado(jcbAlunos);
    }//GEN-LAST:event_jcbAlunosItemStateChanged

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        tipoCadastro = "alterar";
        jtfNome.setEnabled(true);
        jtfCPF.setEnabled(true);
        jtfEmail.setEnabled(true);
        jtfCelular.setEnabled(true);
        jtfEndereco.setEnabled(true);
        jtfID.setEnabled(false);
        btCancelar.setEnabled(true);
        btSalvar.setEnabled(true);
        btAlterar.setEnabled(true);
        btNovo.setEnabled(false);
        btExcluir.setEnabled(false);
        habilitarCampos();


    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o aluno?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {

            int idAluno = Integer.parseInt(jtfID.getText());

            AlunosControl alunosControl = new AlunosControl();
            alunosControl.excluirAluno(idAluno);

            limparCampos();
            listarAlunos();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Alunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcbAlunos;
    private javax.swing.JTextField jtfCPF;
    private javax.swing.JTextField jtfCelular;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbCelular;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbNome;
    // End of variables declaration//GEN-END:variables

}
